// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGlJF2aYDYehYWuVUdskd1fykCydpKzI',
    appId: '1:223184468119:web:927fe506ee9718fc4151d2',
    messagingSenderId: '223184468119',
    projectId: 'spendly-8500e',
    authDomain: 'spendly-8500e.firebaseapp.com',
    storageBucket: 'spendly-8500e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSzTbGrERYHJURqhjKt131h_d3WKjxE-8',
    appId: '1:223184468119:android:9db0dc07da1604734151d2',
    messagingSenderId: '223184468119',
    projectId: 'spendly-8500e',
    storageBucket: 'spendly-8500e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE9bQleYAotwI6QOQfjSMnLAATRCORtHk',
    appId: '1:223184468119:ios:30f7829e57303abb4151d2',
    messagingSenderId: '223184468119',
    projectId: 'spendly-8500e',
    storageBucket: 'spendly-8500e.firebasestorage.app',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE9bQleYAotwI6QOQfjSMnLAATRCORtHk',
    appId: '1:223184468119:ios:30f7829e57303abb4151d2',
    messagingSenderId: '223184468119',
    projectId: 'spendly-8500e',
    storageBucket: 'spendly-8500e.firebasestorage.app',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsGlJF2aYDYehYWuVUdskd1fykCydpKzI',
    appId: '1:223184468119:web:f243ee002eef31764151d2',
    messagingSenderId: '223184468119',
    projectId: 'spendly-8500e',
    authDomain: 'spendly-8500e.firebaseapp.com',
    storageBucket: 'spendly-8500e.firebasestorage.app',
  );
}
